# Generated by Django 5.2.6 on 2025-10-01 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='장르')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='이름')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='프로그램 제목')),
                ('runtime_hour', models.FloatField(verbose_name='상영시간 (시간)')),
                ('poster', models.URLField(max_length=500, verbose_name='포스터 URL')),
                ('description', models.TextField(verbose_name='프로그램 설명')),
                ('program_type', models.CharField(max_length=100, verbose_name='프로그램 타입')),
                ('release', models.IntegerField(verbose_name='개봉년도')),
                ('production', models.CharField(max_length=200, verbose_name='제작사')),
                ('country', models.CharField(max_length=200, verbose_name='제작 국가')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.genre', verbose_name='장르')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramPersonRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100, verbose_name='역할')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_roles', to='backend.person')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_roles', to='backend.program')),
            ],
        ),
        migrations.CreateModel(
            name='Streaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ott', models.CharField(max_length=100, verbose_name='OTT 플랫폼')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streamings', to='backend.program')),
            ],
        ),
        migrations.CreateModel(
            name='SubGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='서브 장르')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.genre', verbose_name='장르')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='sub_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.subgenre', verbose_name='서브 장르'),
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.BigIntegerField(verbose_name='시청 시간')),
                ('views', models.BigIntegerField(verbose_name='조회 수')),
                ('imdb', models.FloatField(verbose_name='IMDB 평점')),
                ('rotten_tomatoes', models.IntegerField(verbose_name='Rotten Tomatoes 평점')),
                ('rank', models.IntegerField(verbose_name='순위')),
                ('half_year', models.CharField(max_length=20, verbose_name='연도 및 반기')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='backend.program')),
            ],
            options={
                'indexes': [models.Index(fields=['half_year'], name='backend_per_half_ye_cf557b_idx')],
            },
        ),
    ]
