# Generated by Django 5.2.6 on 2025-10-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='rotten_tomatoes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rotten Tomatoes 평점'),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(null=True, verbose_name='프로그램 설명'),
        ),
        migrations.AlterField(
            model_name='program',
            name='production',
            field=models.CharField(max_length=200, null=True, verbose_name='제작사'),
        ),
    ]
